MIC-7945: Добавил проверку статуса платежа перед завершение флот оплаты
tinkoff-mobile-tech/AcquiringSdk_IOS pull request #291
Opened 2023-02-09 10:42 UTC by PravosudovTinkoff

2023-02-09 11:32 UTC, akhaman requested changes

2023-02-09 11:32 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +    private var requestRepeatCount: Int
Я бы предложил не хранить тут стейт без лишней на то необходимости. Это свойство можно сделать константным, а модифицированные значения держать только в скоупах функций. Так меньше вероятности в будущем нарваться на какие-то баги

Супер-упрощенный пример:

```swift 
private let maxRequestRepeatsCount: Int

func handleStatus(status: Status) {
     // some logic
     
     doSomething(maxRequestRepeatsCount: self.maxRequestRepeatsCount) {
        ////
      }
     
}

func doSomething(maxRequestRepeatsCount: Int, completion: @escaping Completion) {
    let isAllowed = maxRequestRepeatsCount > 0
    
    if isAllowed {
          // some logic
          doSomething(attempt: maxRequestRepeatsCount - 1, completion: completion)
    }
}

````

2023-02-09 11:32 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +    private var requestRepeatCount: Int
Еще кажется, что этот класс и так довольно сильно перегружен. Давай логику по перезапросам перенесем в отдельную сущность (хоть в paymentStatusService). Тем более, что запросы тут, в СБП и TinkoffPay одни и те же - проще переиспользовать

2023-02-09 11:32 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +    private var requestRepeatCount: Int
и валидацию статусов туда же

2023-02-09 11:32 UTC, akhaman commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +            delegatePaymentWasCancelled(paymentProcess: paymentProcess, cardId: cardId, rebillId: rebillId)
А это точно отмена? кажется, что нет:
Отмена - это 
- когда бек там что-то отменил
- пользователь сам что-то отменил

2023-02-09 11:35 UTC, PravosudovTinkoff commented on TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift
> +            delegatePaymentWasCancelled(paymentProcess: paymentProcess, cardId: cardId, rebillId: rebillId)
все вопросы к спешке

2023-02-13 12:10 UTC, akhaman approved these changes

2023-02-13 16:03 UTC, merged